apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dex-worker
  labels:
    app: dex
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dex
        tier: worker
    spec:
      containers:
        - name: dex-worker
          image: quay.io/coreos/dex:v0.5.1
          command: [
            "/bin/sh", "-c",
            "/opt/dex/bin/dex-worker --listen=http://0.0.0.0:5556 --db-url=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DEX_POSTGRES_SERVICE_HOST}:${DEX_POSTGRES_SERVICE_PORT}/${POSTGRES_USER}?sslmode=disable --email-cfg=/opt/dex/email/emailer.json --enable-registration=true --log-debug=true"
          ]
          ports:
            - containerPort: 5556
          env:
          - name: DEX_WORKER_ADMIN_API_SECRET
            valueFrom:
              secretKeyRef:
                name: dex
                key: api-secret
          - name: DEX_WORKER_KEY_SECRETS
            valueFrom:
              secretKeyRef:
                name: dex
                key: key-secret
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: user

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dex
  name: dex-worker
spec:
  ports:
  - port: 80
    targetPort: 5556
  selector:
    app: dex
    tier: worker
  type: LoadBalancer
