apiVersion: batch/v1
kind: Job
metadata:
  name: dex-connector-setup
  labels:
    app: dex
spec:
  template:
    metadata:
      name: dex-connector-setup
      labels:
        app: dex
        tier: web
    spec:
      volumes:
      - name: dex
        secret:
          secretName: dex
      containers:
      - name: dex-connector-setup
        image: andyhd/csd-sso-dex:v4
        command: [
          "/opt/dex/bin/dexctl",
          "set-connector-configs",
          "/etc/dex/connectors"
        ]
        volumeMounts:
        - name: dex
          mountPath: /etc/dex
          readOnly: true
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: user
        - name: DEXCTL_DB_URL
          value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DEX_POSTGRES_SERVICE_HOST):$(DEX_POSTGRES_SERVICE_PORT)/$(POSTGRES_USER)?sslmode=disable
        - name: DEXCTL_LOG_DEBUG
          value: "true"
      restartPolicy: Never
