apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dex-worker
  labels:
    app: dex
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dex
        tier: worker
    spec:
      containers:
        - name: dex-worker
          image: andyhd/csd-sso-dex:v4
          command: [
            "/opt/dex/bin/dex-worker"
          ]
          ports:
            - containerPort: 5556
          env:
          - name: DEX_WORKER_LISTEN
            value: http://0.0.0.0:5556
          - name: DEX_WORKER_ADMIN_API_SECRET
            valueFrom:
              secretKeyRef:
                name: dex
                key: api-secret
          - name: DEX_WORKER_KEY_SECRETS
            valueFrom:
              secretKeyRef:
                name: dex
                key: key-secret
          - name: ISSUER_DOMAIN_SUFFIX
            valueFrom:
              secretKeyRef:
                name: dex
                key: issuer-domain-suffix
          - name: ISSUER_DOMAIN_PROTOCOL
            valueFrom:
              secretKeyRef:
                name: dex
                key: issuer-domain-protocol
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: user
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DEX_WORKER_DB_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DEX_POSTGRES_SERVICE_HOST):$(DEX_POSTGRES_SERVICE_PORT)/$(POSTGRES_USER)?sslmode=disable
          - name: DEX_WORKER_EMAIL_CFG
            value: /opt/dex/email/emailer.json
          - name: DEX_WORKER_ENABLE_AUTOMATIC_REGISTRATION
            value: "true"
          - name: DEX_WORKER_LOG_DEBUG
            value: "true"
          - name: DEX_WORKER_LOG_TIMESTAMPS
            value: "true"
          - name: DEX_WORKER_ISSUER
            value: $(ISSUER_DOMAIN_PROTOCOL)://$(POD_NAMESPACE).$(ISSUER_DOMAIN_SUFFIX)

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dex
  name: dex-worker
spec:
  ports:
  - port: 80
    targetPort: 5556
  selector:
    app: dex
    tier: worker
  type: LoadBalancer
