apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dex-overlord
  labels:
    app: dex
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dex
        tier: overlord
    spec:
      containers:
        - name: dex-overlord
          image: andyhd/csd-sso-dex:v4
          command: [
            "/opt/dex/bin/dex-overlord"
          ]
          env:
          - name: DEX_OVERLORD_ADMIN_API_SECRET
            valueFrom:
              secretKeyRef:
                name: dex
                key: api-secret
          - name: DEX_OVERLORD_KEY_SECRETS
            valueFrom:
              secretKeyRef:
                name: dex
                key: key-secret
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: user
          - name: DEX_OVERLORD_DB_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DEX_POSTGRES_SERVICE_HOST):$(DEX_POSTGRES_SERVICE_PORT)/$(POSTGRES_USER)?sslmode=disable
          - name: DEX_OVERLORD_LOG_DEBUG
            value: "true"
          - name: DEX_OVERLORD_LOG_TIMESTAMPS
            value: "true"
