apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: openidm
spec:
  ports:
    - port: 5432
  selector:
    app: openidm
    tier: postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openidm-postgres-pv-claim
  labels:
    app: openidm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openidm-postgres
  labels:
    app: openidm
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dex
        tier: postgres
    spec:
      containers:
      - image: forgerock/openidm-postgres
        name: postgres
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openidm-postgres
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: openidm-postgres
              key: user
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: openidm-postgres-storage
          mountPath: /var/lib/postgresql
      volumes:
      - name: openidm-postgres-storage
        persistentVolumeClaim:
          claimName: openidm-postgres-pv-claim
