---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openam
  labels:
    app: openam
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openam
        tier: web
    spec:
      containers:
        - name: openam
          image: forgerock/openam:latest
          ports:
            - containerPort: 8080
            - containerPort: 8443


---
apiVersion: v1
kind: Service
metadata:
  name: openam
  labels:
    app: openam
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: openam
    tier: web
  type: LoadBalancer
