version: '2'
services:

  openam:
    image: forgerock/openam:latest
    ports:
      - "8080:8080"
      - "8443:8443"

  openidm-postgres:
    image: forgerock/openidm-postgres
    volumes:
      - /tmp/pg:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: openidm
      POSTGRES_USER: openidm

  openidm:
    image: forgerock/openidm:latest
    ports:
     - "8081:8080"
    links:
     - openidm-postgres:postgres

  opendj:
    image: forgerock/opendj:latest
    ports:
     - "389:389"
    environment:
      BOOTSTRAP: /opt/opendj/bootstrap/cts/setup.sh
    volumes:
      - /tmp/opendj:/opt/opendj/data
      - ./secrets:/var/secrets/opendj
