apiVersion: v1
kind: Service
metadata:
  name: signonotron2-redis
  labels:
    app: signonotron2
spec:
  ports:
    - port: 6379
  selector:
    app: signonotron2
    tier: redis

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: signonotron2-redis
  labels:
    app: signonotron2
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: signonotron2
        tier: redis
    spec:
      containers:
      - image: redis:3.2.1
        name: redis
