apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  root-password: RUhtaEVUWXR4bDM3TElLaDZIazI1cGVuNWVvbg==
  password: UXJxTVR0aTYqeE42eUNDNTFRZlIzUjZHUFEoTw==
  user: QXRyYTFKOXxGOWlSaGN4MGQ3RmVJOGJ0Lk1OVA==
  database-name: ajk3eDFrYUVidklvMlFjTUpwcktMVzVXOHBUUg==
